=== ChiaraBi/asclepias-broker/legacy/asclepias_broker/jsonschemas/event.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://raw.githubusercontent.com/asclepias/event-model/master/jsonschema/event.json",
  "title": "Event message schema.",
  "description": "Schema of the event message.",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "ID": {
      "type": "string",
      "description": "Globally unique identifier of the event (UUID version 4 as specified in RFC 4122)."
    },
    "Description": {
      "type": "string",
      "description": "Free-text description of the event."
    },
    "EventType": {
      "type": "string",
      "description": "Type of the event. Controlled vocabulary: 'RelationshipCreated' or 'RelationshipDeleted'",
      "enum": ["RelationshipCreated", "RelationshipDeleted"]

    },
    "Time": {
      "type": "string",
      "description": "Time when the payload information was created."
    },
    "Creator": {
      "type": "string",
      "description": "Name of the party, which emmited this event."
    },
    "Source": {
      "type": "string",
      "description": "Name of the source, algorithm or procedure, which created this event."
    },
    "Payload": {
      "type": "array",
      "description": "Payload information specific to the EventType. An array, containing one or more payloads of the structure matching with the EventType.",
      "items": {
        "$ref": "scholix-v3.json"
      }
    }
  },
  "required": [
    "ID",
    "EventType",
    "Time",
    "Creator",
    "Source",
    "Payload"
  ]
}

=== ChiaraBi/asclepias-broker/examples/ads-events.json
{
  "Description": "ADS citation events",
  "Creator": "ADS",
  "Source": "ADS.Discovery",
  "Time": "1508531201",
  "ID": "b11374c4-e9c1-447d-931a-331c6b500eb6",
  "EventType": "RelationshipCreated",
  "Payload": [
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2016arXiv161208077M",
          "ID": "2016arXiv161208077M"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "doi",
          "IDURL": "https://doi.org/10.5281/zenodo.573267",
          "ID": "10.5281/zenodo.573267"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2016arXiv161208077M",
          "ID": "2016arXiv161208077M"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "doi",
          "IDURL": "https://doi.org/10.5281/zenodo.819449",
          "ID": "10.5281/zenodo.819449"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2016arXiv161003216L",
          "ID": "2016arXiv161003216L"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "doi",
          "IDURL": "https://doi.org/10.5281/zenodo.53155",
          "ID": "10.5281/zenodo.53155"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2016arXiv161208077M",
          "ID": "2016arXiv161208077M"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "doi",
          "IDURL": "https://doi.org/10.5281/zenodo.819452",
          "ID": "10.5281/zenodo.819452"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2016arXiv161208077M",
          "ID": "2016arXiv161208077M"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "doi",
          "IDURL": "https://doi.org/10.5281/zenodo.819453",
          "ID": "10.5281/zenodo.819453"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2016arXiv161208077M",
          "ID": "2016arXiv161208077M"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "doi",
          "IDURL": "https://doi.org/10.5281/zenodo.819451",
          "ID": "10.5281/zenodo.819451"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2017AJ....154...28B",
          "ID": "2017AJ....154...28B"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "ascl",
          "IDURL": "http://ascl.net/1205.004",
          "ID": "1205.004"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2017ApJ...843...63F",
          "ID": "2017ApJ...843...63F"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "ascl",
          "IDURL": "http://ascl.net/1202.015",
          "ID": "1202.015"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2016arXiv161208077M",
          "ID": "2016arXiv161208077M"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "doi",
          "IDURL": "https://doi.org/10.5281/zenodo.819448",
          "ID": "10.5281/zenodo.819448"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2017arXiv170607837L",
          "ID": "2017arXiv170607837L"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "ascl",
          "IDURL": "http://ascl.net/1105.003",
          "ID": "1105.003"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2017ApJ...844....8S",
          "ID": "2017ApJ...844....8S"
        },
        "Type": {
          "Name": "unknown"
        }
      },
      "LicenseURL": "https://creativecommons.org/publicdomain/zero/1.0/",
      "Target": {
        "Identifier": {
          "IDScheme": "ascl",
          "IDURL": "http://ascl.net/1502.021",
          "ID": "1502.021"
        },
        "Type": {
          "Name": "software"
        }
      },
      "LinkPublicationDate": "2018-01-01",
      "LinkProvider": [
        {
          "Name": "SAO/NASA Astrophysics Data System"
        }
      ]
    },
    {
      "RelationshipType": {
        "SubTypeSchema": "DataCite",
        "SubType": "Cites",
        "Name": "References"
      },
      "Source": {
        "Identifier": {
          "IDScheme": "ads",
          "IDURL": "http://adsabs.harvard.edu/abs/2016arXiv161208077M",
